import { Products } from "@pc-builder/shared/part";

export const SAMPLE_TEMPLATES: Partial<Record<Products, Record<string, unknown>>> = {
  [Products.MAIN]: {
    Model: "Z790 AORUS XTREME X ICE",
    Brand: "Gigabyte",
    USB: "Chipset+Intel® Thunderbolt™ 4 Controller:\n<ol>\n<li>2 x USB Type-C® ports on the back panel, with USB 3.2 Gen 2 support</li>\n</ol>\n\nChipset:\n<ol>\n<li>2 x USB Type-C® ports with USB 3.2 Gen 2x2 support, available through the internal USB header</li>\n<li>2 x USB 3.2 Gen 2 Type-A ports (red) on the back panel</li>\n</ol>",
    "Back Panel Connectors":
      "<ol>\n<li>10 x USB 3.2 Gen 2 Type-A ports (red)</li>\n<li>2 x RJ-45 ports</li>\n</ol>",
    "Form Factor": "E-ATX Form Factor; 30.5cm x 28.5cm",
    Chipset: "Intel Z790 Express Chipset",
  },
  [Products.CPU]: {
    Model: "Intel Core i9-14900K",
    Brand: "Intel",
    CPU: "Intel Core i9-14900K",
    Cores: "24 cores (8 P-cores + 16 E-cores)",
    "L3 Cache": "36 MB Smart Cache",
    TDP: "125 W",
  },
  [Products.GPU]: {
    Model: "NVIDIA GeForce RTX 4090",
    Brand: "NVIDIA",
    "Core Clock": "2235 MHz",
    "Boost Clock": "2520 MHz",
    "Memory Size": "24 GB",
    "Memory Type": "GDDR6X",
  },
  [Products.GRAPHIC_CARD]: {
    Model: "ASUS ROG Strix RTX 4080 Super",
    Brand: "ASUS",
    cardwidth: "150 mm",
    cardlength: "357 mm",
    cardheight: "70 mm",
    recommendedpower: "850 W",
    outputs: "2x HDMI 2.1a | 3x DisplayPort 1.4a",
  },
  [Products.RAM]: {
    Model: "G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5 6000MHz",
    Brand: "G.Skill",
    memoryspeed: "6000 MHz",
    memorysize: "32 GB",
    modules: "2x 16 GB",
    ddrtype: "DDR5",
  },
  [Products.SSD]: {
    Model: "Samsung 990 Pro 2TB M.2 NVMe SSD",
    Brand: "Samsung",
    size: "2 TB",
    formfactor: "M.2 2280",
    storageinterface: "PCIe Gen 4.0 x4",
    readspeed: "7450 MB/s",
    writespeed: "6900 MB/s",
  },
  [Products.HDD]: {
    Model: 'Seagate BarraCuda 2TB 3.5" HDD',
    Brand: "Seagate",
    storagesize: "2 TB",
    formfactor: "3.5 inch",
    storageinterface: "SATA III",
    rpm: "7200 RPM",
  },
  [Products.PSU]: {
    Model: "Corsair RM1000x 1000W PSU",
    Brand: "Corsair",
    poweroutput: "1000 W",
    certification: "80 Plus Gold",
    modularity: "Fully Modular",
  },
  [Products.CASE]: {
    Model: "Lian Li PC-O11 Dynamic EVO",
    Brand: "Lian Li",
    casetype: "Mid Tower",
    motherboardsupport: "E-ATX, ATX, Micro-ATX, Mini-ITX",
    cpucoolerheight: "167 mm",
    maxpsulength: "220 mm",
  },
  [Products.COOLER]: {
    Model: "Noctua NH-D15 chromax.black",
    Brand: "Noctua",
    socketsupported: "LGA1700, LGA1200, AM4, AM5",
    fansize: "140 mm",
    fancount: "2 fans",
    rpm: "1500 RPM",
  },
  [Products.AIO]: {
    Model: "Corsair iCUE H150i Elite Capellix XT",
    Brand: "Corsair",
    socketssupported: "LGA1700, LGA1200, AM4, AM5",
    radiatorsize: "360 mm",
    fansize: "120 mm",
  },
};
