services:
  nestjs-prod:
    build:
      context: ../../
      dockerfile: ./docker/nestjs/Dockerfile
      target: prod
    ports:
      - 5000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MONGO_HOST=mongo:27017
      - DATABASE_NAME=${DATABASE_NAME:-PC_Builder}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-NestjsApp}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?error}
      - JWT_SECRET=${JWT_SECRET:?error}
      - CSRF_SECRET=${CSRF_SECRET:?error}
    profiles:
      - production
  nestjs-dev:
    build:
      context: ../../
      dockerfile: ./docker/nestjs/Dockerfile
      target: dev
    ports:
      - 5000:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MONGO_HOST=mongo:27017
      - DATABASE_NAME=${DATABASE_NAME:-PC_Builder}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-NestjsApp}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?error}
      - JWT_SECRET=${JWT_SECRET:?error}
      - CSRF_SECRET=${CSRF_SECRET:?error}
    profiles:
      - development
    develop:
      watch:
        - action: sync
          path: ../../apps/backend
          target: /usr/local/app/apps/backend
        - action: sync
          path: ../../packages/shared
          target: /usr/local/app/packages/shared
        - action: rebuild
          path: ../../package.json
        - action: rebuild
          path: ../../apps/backend/package.json
        - action: rebuild
          path: ../../package-lock.json
