include:
  - ./docker/database/compose.yaml
  - ./docker/nestjs/compose.yaml
  - ./docker/nextjs/compose.yaml
  - ./docker/nginx/compose.yaml
  - ./docker/crawler/compose.yaml
  - ./docker/mcp-server/compose.yaml
