services:
  nginx-prod:
    build:
      context: .
      target: prod
    ports:
      - 3000:80
    profiles:
      - production
  nginx-dev:
    build:
      context: .
      target: dev
    ports:
      - 3000:80
    profiles:
      - development
