services:
  nginx-prod:
    build:
      context: .
      target: prod
    ports:
      - 3000:80
    profiles:
      - production
    depends_on:
      nestjs-prod:
        condition: service_healthy
      nextjs-prod:
        condition: service_healthy
    volumes:
      - ../../.cdn-data:/usr/share/nginx/html/cdn:ro
  nginx-dev:
    build:
      context: .
      target: dev
    ports:
      - 3000:80
    profiles:
      - development
    depends_on:
      nestjs-dev:
        condition: service_healthy
      nextjs-dev:
        condition: service_healthy
    volumes:
      - ../../.cdn-data:/usr/share/nginx/html/cdn:ro
