services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - Mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME:-PC_Builder}
      - MYSQL_USER=${DATABASE_USERNAME:-NestjsApp}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD:?error}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD:?error}
volumes:
  Mysql:
