services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - Mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=PC_Builder
      - MYSQL_USER=NestjsApp
    env_file:
      - .env
volumes:
  Mysql:
