services:
  nextjs-prod:
    build:
      context: ../../
      dockerfile: ./docker/nextjs/Dockerfile
      target: prod
    ports:
      - 4000:3000
    environment:
      - BACKEND_HOST=http://nestjs-prod:3000
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=PC_Builder
      - DATABASE_USERNAME=NestjsApp
    env_file:
      - .env
    profiles:
      - production
  nextjs-dev:
    build:
      context: ../../
      dockerfile: ./docker/nextjs/Dockerfile
      target: dev
    ports:
      - 4000:3000
    environment:
      - BACKEND_HOST=http://nestjs-dev:3000
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=PC_Builder
      - DATABASE_USERNAME=NestjsApp
    env_file:
      - .env
    profiles:
      - development
    develop:
      watch:
        - action: sync
          path: ../../
          target: /usr/local/app
          ignore:
            - crawlers
            - docker
            - nest-cli.json
